version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${APP_PORT:-3000}:3000
  
  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-app}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    ports:
      - 3606:3306
    volumes:
      - ./tmp/mariadb:/var/lib/mysql
  
  adminer:
    image: adminer
    environment:
        ADMINER_DESIGN: mvt
        ADMINER_DEFAULT_SERVER: db
    ports:
        - ${ADMINER_PORT:-8080}:8080